url="https://blog.5-23.dev/p/{starix.id}/"
thumb="https://github.com/5-23/blog/blob/main/src/content/posts/{starix.id}/thumb.jpg?raw=true"
name="Asta blog"
avatar="https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-19/435144802_1203396984152114_3745663638057015361_n.jpg?_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_cat=102&_nc_ohc=6Yhi0nM3iV4Q7kNvgE6hvMi&edm=AEhyXUkBAAAA&ccb=7-5&oh=00_AYBRcFR79Oukb8YNGJTWLSrNu8XxI6smXzhKea4yFBZuTw&oe=66C41004&_nc_sid=8f1549"

[post]
content="@everyone `{starix.id}`가 올라왔어요!"
color="#2E7EFF"

[fix]
content=""
color="#FF782E"
